package modelos;
// Generated 01-jun-2024 18:16:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ascensos generated by hbm2java
 */
public class Ascensos  implements java.io.Serializable {


     private int id;
     private String cargo;
     private Date fechaInicio;
     private Date fechaFin;
     private String jefeDepartamento;
     private String requisitos;

    public Ascensos() {
    }

	
    public Ascensos(int id, String cargo, Date fechaInicio, String jefeDepartamento) {
        this.id = id;
        this.cargo = cargo;
        this.fechaInicio = fechaInicio;
        this.jefeDepartamento = jefeDepartamento;
    }
    public Ascensos(int id, String cargo, Date fechaInicio, Date fechaFin, String jefeDepartamento, String requisitos) {
       this.id = id;
       this.cargo = cargo;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.jefeDepartamento = jefeDepartamento;
       this.requisitos = requisitos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getJefeDepartamento() {
        return this.jefeDepartamento;
    }
    
    public void setJefeDepartamento(String jefeDepartamento) {
        this.jefeDepartamento = jefeDepartamento;
    }
    public String getRequisitos() {
        return this.requisitos;
    }
    
    public void setRequisitos(String requisitos) {
        this.requisitos = requisitos;
    }




}


