package modelos;
// Generated 01-jun-2024 18:16:29 by Hibernate Tools 4.3.1



/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String gerente;
     private String descripcion;

    public Departamento() {
    }

	
    public Departamento(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Departamento(int id, String nombre, String gerente, String descripcion) {
       this.id = id;
       this.nombre = nombre;
       this.gerente = gerente;
       this.descripcion = descripcion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getGerente() {
        return this.gerente;
    }
    
    public void setGerente(String gerente) {
        this.gerente = gerente;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


