package modelos;
// Generated 01-jun-2024 18:16:29 by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private String apellidos;
     private String direccion;
     private String cargo;
     private int departamento;
     private Integer idAscensos;
     private String contrasena;

    public Empleado() {
    }

	
    public Empleado(String dni, String nombre, String apellidos, int departamento, String contrasena) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.departamento = departamento;
        this.contrasena = contrasena;
    }
    public Empleado(String dni, String nombre, String apellidos, String direccion, String cargo, int departamento, Integer idAscensos, String contrasena) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.cargo = cargo;
       this.departamento = departamento;
       this.idAscensos = idAscensos;
       this.contrasena = contrasena;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public int getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(int departamento) {
        this.departamento = departamento;
    }
    public Integer getIdAscensos() {
        return this.idAscensos;
    }
    
    public void setIdAscensos(Integer idAscensos) {
        this.idAscensos = idAscensos;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }




}


