package modelos;
// Generated 01-jun-2024 18:16:29 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Evaluacion generated by hbm2java
 */
public class Evaluacion  implements java.io.Serializable {


     private int id;
     private String dni;
     private int anyo;
     private int companyerismo;
     private int eficiencia;
     private int iniciativa;
     private int liderazgo;
     private BigDecimal notaMedia;

    public Evaluacion() {
    }

    public Evaluacion(int id, String dni, int anyo, int companyerismo, int eficiencia, int iniciativa, int liderazgo, BigDecimal notaMedia) {
       this.id = id;
       this.dni = dni;
       this.anyo = anyo;
       this.companyerismo = companyerismo;
       this.eficiencia = eficiencia;
       this.iniciativa = iniciativa;
       this.liderazgo = liderazgo;
       this.notaMedia = notaMedia;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public int getAnyo() {
        return this.anyo;
    }
    
    public void setAnyo(int anyo) {
        this.anyo = anyo;
    }
    public int getCompanyerismo() {
        return this.companyerismo;
    }
    
    public void setCompanyerismo(int companyerismo) {
        this.companyerismo = companyerismo;
    }
    public int getEficiencia() {
        return this.eficiencia;
    }
    
    public void setEficiencia(int eficiencia) {
        this.eficiencia = eficiencia;
    }
    public int getIniciativa() {
        return this.iniciativa;
    }
    
    public void setIniciativa(int iniciativa) {
        this.iniciativa = iniciativa;
    }
    public int getLiderazgo() {
        return this.liderazgo;
    }
    
    public void setLiderazgo(int liderazgo) {
        this.liderazgo = liderazgo;
    }
    public BigDecimal getNotaMedia() {
        return this.notaMedia;
    }
    
    public void setNotaMedia(BigDecimal notaMedia) {
        this.notaMedia = notaMedia;
    }




}


