package modelos;
// Generated 01-jun-2024 18:16:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Vacaciones generated by hbm2java
 */
public class Vacaciones  implements java.io.Serializable {


     private int id;
     private String dni;
     private Date fechaInicio;
     private Date fechaFin;
     private String motivo;

    public Vacaciones() {
    }

	
    public Vacaciones(int id, String dni, Date fechaInicio, Date fechaFin) {
        this.id = id;
        this.dni = dni;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }
    public Vacaciones(int id, String dni, Date fechaInicio, Date fechaFin, String motivo) {
       this.id = id;
       this.dni = dni;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.motivo = motivo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }




}


